# 便利な標準関数たち

## 演算系

In [4]:
println(div(5,2), div(-5,2))#切り捨て
println(fld(5,2), fld(-5,2))#切り下げ　floor division
println(cld(5,2), fld(-5,2))#切り上げ　ceiling division

2-2
2-3
3-3


- RoundToZero 切り捨て
- RoundDonw 切り下げ
- RoundUp 切り上げ
- RoundNearest 最近接丸め(偶数)
- RoundNearestTiesAway 最近接丸め(0から遠いほう)
- RoundNearestTiesUP 最近接丸め(切り上げ)

In [5]:
div(5,2,RoundNearestTiesAway)

3

In [6]:
÷(-5,2,RoundDown)

-3

- %,rem 整数剰余算(切り捨て)
- mod 整数剰余算(切り下げ)　

In [1]:
divrem(4.3,1.2)

(3.0, 0.7)

In [3]:
dayofweek(date) = mod1(days(date),7)
days_of_week = ["Monday" , "Tuesday" , "Wednesday" , "Thursday", "Friday" ,"Saturday" ,"Sunday"]
dayname(date) = days_of_week[dayofweek]

dayname (generic function with 1 method)

In [16]:
mod(2+2π , 2pi)
mod2pi(10)
rem2pi(80,RoundDown)

4.6017763138449626

行列演算では有用らしい

In [18]:
2\3

1.5

### 積和演算
x * y + z
- fma() 精度優先
- muladd() パフォーマンス優先

In [20]:
fma(0.1,0.2,0.3)
muladd(0.1,0.2,0.3)

0.32

### 剰余演算

オーバーフローしないようになっている

In [21]:
powermod(5,2,20) # == mod(5^2,20)

5

### 演算系
- sign(x) 符号関数
- sign(y) 符号関数 true false
- cmp(x,y) 比較関数
- abs(x) 絶対値
- abs2(x) 絶対値の2乗
- copysign(x,y) abs(x)*sign(y)
- flipsign(x,y) x*sign(y)
- sqrt(x)
- isqrt(x) 整数平方根
- cbrt(x) 立方根

### 数学系
- sin 正弦
- cos 余弦
- tan 正接
- asin 逆正弦
- acos 逆余弦
- atan 逆正接
- atan(x,y) arctan(y/x)
- exp 指数
- log 自然対数
- log(b,x) bを底とする対数
- sinh 双曲正弦
- cosh 双曲余弦
- tanh 双曲正接
- asinh 
- acosh
- atanh
- sec
- csc
- cot
- asec
- acot
- log10
- log2
- log1p log(x + 1)
- deg2rad 度 → ラジアン
- rad2deg
- 三角関数にdをつければ度数法
- sinpi sin(π*x)
- cospi
- tanpi
- sincos (sin(x), cos(x))
- sincospi
- cis exp(i*im)
- cispi cis(π*x)
- factorial n!
- bionomial nCm
- gcd(a,b...)
- gcdx() 最大公約数 + ベズー係数

### 文字・文字列情報取得関数・演算子
- length
- sizeof
- ncodeunits
- codepoint
- codeunits
- codeunit
- s[i] インデクシング
- @view s[i] 部分文字列抽出
- first(s) 文字列の最初の文字
- frist(s,n)
- last(s)
- last(s,n)
- firstindex(s) 文字列最初のインデックス
- lastindex(s) 文字列最後のインデックス
- thisind(s,i)
- prevind(s,i)
- eachindex(s)
- keys(s) 
- textwidth(s) 文字列の表示幅

### 文字・文字列比較関数・演算子
- == 等価演算子
- != ,≠ 非等価演算子
- < <= > >=
- cmp 辞書式大小比較
- c in S \in \notin

### 文字列操作関数・演算子
- string(v..) 文字列化関数
- s*t 文字列連結
- s^n , repeat(s,n) 文字列リピート
- uppercase(s) 小文字を大文字に変換
- lowercase(s) 大文字を小文字に変換
- uppercasefirst(s) 文字列の最初の文字を大文字に変換
- lowercasefirst(s)
- titlecase(s) 文字列の最初の文字を大文字に，それ以外を小文字に
- join(collection ,delim)コレクションの各要素をdelimで連結した文字列を生成
- chop(s) 文字列の末尾の文字除去
- chomp(s) 文字列末尾の改行文字除去
- split(s) rsplit(s) ホワイトスペースによる文字列分割
- split(s,pattern) rsplit(s,pattern) patternによる文字列分割
- strip(s) lstrip(s) rstrip(s) 文字列の先頭，末尾のホワイトスペースの除去
- strip(s,chars),lstrip(s,chars),rstrip(s,chars) 文字列の先頭/末尾の特定文字の除去
- strip(fn,s),lstrip(fn,s),rstrip(fn,s) 文字列の先頭/末尾の特定文字の除去
- lpad(s,l.pad=' '),rpad(s,l,pad=' ') 文字列の行埋め
- reverse() 文字列反転

### 文字列検索･置換関連関数
- match(r::Regex, s) 正規表現マッチ
- each(r::Regex, s) 正規表現マッチイテレーション
- findfirst(pattern .s,) パターン検索(先頭から)
- findnext(patten,s,i) パターン検索(iバイト目以降)
- findlast(ptnstr,s) 文字列検索(末尾から)
- findprev(prnstr, s, i)文字列検索(iバイト目以前)
- findall(pattern,s) パターン検索
- count(patten,s) パターン検索(件数)
- occursin(patten,s) パターンが含まれるか否か
- contains(s,pattern) 同上
- startswith(s,pattern) パターンで始まるか否か
- endswith(s,pattern) パターンで終わるか否か
- replace(s,patten=>subst) 文字列置換

### Julia の正規表現
- ^ 先頭 
- | 代替
- . 任意の1文字
- * 直前のパターンの0回以上の繰り返し
- + 直前のパターンの1回以上の繰り返し
- {n,m} 直前のパターンのn回以上m回以下の繰り返し {n} n回の繰り返し
- [a-z] 文字クラス
- \s ホワイトスペース
- \d 数字
- \w 単語構成文字
- (...) キャプチャグループ
- (?<name>...) 名前付きキャプチャグループ

#### 正規表現のモードフラグ
- i 大文字小文字区別しない
- m 複数行モード
- s 任意の1文字が改行にもマッチ
- a ASCIIモード
- x コメントモード

In [24]:
m = match(r"\d+","123dfaisfjhaklj54") 
m.match

"123"

In [27]:
m = match(r"(\d+)(?<ABC>[ABC]+)","123ABCdfaisfABCjhaklj54") 
m.match

"123ABC"

In [29]:
for m in eachmatch(r"\w+","Yes, I have a number.")
  println(m.match)
end

Yes
I
have
a
number


- \0 マッチした部分文字列 m.match
- \1 \2 キャプチャグループ
- \g<1> 
- \g < name >

In [9]:
replace("123ABCあいう漢字",r"\d"=> s"\0\0")

"112233ABCあいう漢字"

In [10]:
replace("123ABCあいう漢字",r"\d"=> s"\g<0>1")

"112131ABCあいう漢字"

In [15]:
replace("123ABCあいう漢字",r"(\d+)(?<abc>[a-z]+)"ia=>s"\g<abc>\1")

"ABC123あいう漢字"

- length
- isempty
- in A 
- eltype
- ndims
- size 配列のサイズ
- axes インデックス範囲

In [16]:
A = [100z + 10y + x for x = 1:3 ,y = 1:4 , z= 1:2];
ndims(A)

3

In [17]:
size(A)

(3, 4, 2)

In [18]:
axes(A)

(Base.OneTo(3), Base.OneTo(4), Base.OneTo(2))

In [19]:
axes(A,2)

Base.OneTo(4)

In [20]:
for x in axes(A,1) ,y in axes(A,2) ,z in axes(A,3)
  println(A[x,y,z])
end

111
211
121
221
131
231
141
241
112
212
122
222
132
232
142
242
113
213
123
223
133
233
143
243


### 配列生成演算子

In [21]:
axes((:a,:b,:c))

(Base.OneTo(3),)

In [25]:
Vector{Int}(undef,5)

5-element Vector{Int64}:
 140415472932248
 140415472917424
 140415473006272
 140415472943304
 140415255046784

In [26]:
Matrix{Float64}(undef,2,2)

2×2 Matrix{Float64}:
 6.93745e-310  6.93744e-310
 6.93744e-310  6.93744e-310

In [30]:
Array{UInt8}(undef,2,3,2)

2×3×2 Array{UInt8, 3}:
[:, :, 1] =
 0xb0  0xa3  0xb5
 0x19  0x03  0x7f

[:, :, 2] =
 0x00  0x08  0x5f
 0x00  0xf0  0x06

In [31]:
zeros(Int,5)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

In [32]:
ones(2,2)

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [33]:
fill(0x7f,2,2)

2×2 Matrix{UInt8}:
 0x7f  0x7f
 0x7f  0x7f

In [34]:
BitArray(undef,12,13)

12×13 BitMatrix:
 0  0  1  1  0  0  0  1  1  1  0  0  0
 0  0  1  1  0  0  0  1  0  1  0  0  0
 0  0  0  0  0  0  0  1  1  1  0  0  0
 0  0  0  1  0  0  1  0  0  0  0  0  0
 1  1  0  1  0  0  0  1  1  0  0  0  0
 0  0  0  1  0  0  0  1  1  0  0  0  0
 1  0  0  1  0  0  0  0  0  0  0  0  0
 0  0  0  1  0  0  0  0  1  0  0  0  0
 0  1  1  1  0  1  1  0  1  0  0  0  0
 0  1  0  1  0  0  0  0  1  0  0  0  0
 0  1  1  1  0  0  0  0  1  0  0  0  0
 1  0  0  0  0  1  0  0  1  0  0  0  0

In [35]:
trues(3,4,2)

3×4×2 BitArray{3}:
[:, :, 1] =
 1  1  1  1
 1  1  1  1
 1  1  1  1

[:, :, 2] =
 1  1  1  1
 1  1  1  1
 1  1  1  1

In [37]:
typeof(1:2:10 .== [2,33,34,12,30])

BitVector (alias for BitArray{1})

In [38]:
A = UInt8[1 2 ; 3 4]

2×2 Matrix{UInt8}:
 0x01  0x02
 0x03  0x04

In [39]:
similar(A,3,4,2)

3×4×2 Array{UInt8, 3}:
[:, :, 1] =
 0x00  0x00  0x00  0x60
 0x00  0x00  0x00  0xd9
 0x00  0x00  0x70  0xfd

[:, :, 2] =
 0xb4  0x00  0xd9  0x7f
 0x7f  0x60  0xfd  0x00
 0x00  0x80  0xb4  0x00

In [40]:
similar(A,Float32)

2×2 Matrix{Float32}:
 7.41727f-37  2.7981f-35
 4.5813f-41   4.5813f-41

In [41]:
B = BitArray(undef,2,2)

2×2 BitMatrix:
 0  0
 0  0

In [42]:
similar(B,10)

10-element BitVector:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [45]:
A = [1 2 ;3 4];
x = [-1 ; 1];
y = A*x

2-element Vector{Int64}:
 1
 1

In [57]:
A = [1 2 ; 3 4];
x = [-1 : 1];
println(transpose(A))
println(A')
println(A'A)
C = [1-1im 2 + 3im ; 3ℯ^2 + im  π]
println(transpose(C))
println(C')

[1 3; 2 4]
[1 3; 2 4]
[10 14; 14 20]
ComplexF64[1.0 - 1.0im 22.16716829679195 + 1.0im; 2.0 + 3.0im 3.141592653589793 + 0.0im]
ComplexF64[1.0 + 1.0im 22.16716829679195 - 1.0im; 2.0 - 3.0im 3.141592653589793 - 0.0im]


In [58]:
q = [1,2,3,4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [59]:
push!(q,12,32)

6-element Vector{Int64}:
  1
  2
  3
  4
 12
 32

In [60]:
pop!(q)

32

In [61]:
pop!(q)

12

In [62]:
q

4-element Vector{Int64}:
 1
 2
 3
 4

In [63]:
pushfirst!(q,-2,-1)

6-element Vector{Int64}:
 -2
 -1
  1
  2
  3
  4

In [64]:
popfirst!(q)

-2

In [65]:
prepend!(append!(q, 6:9),-2:0)

12-element Vector{Int64}:
 -2
 -1
  0
 -1
  1
  2
  3
  4
  6
  7
  8
  9

In [67]:
popat!(q,4)
q

10-element Vector{Int64}:
 -2
 -1
  0
  2
  3
  4
  6
  7
  8
  9

In [68]:
deleteat!(q,3:4)

8-element Vector{Int64}:
 -2
 -1
  3
  4
  6
  7
  8
  9

In [69]:
popat!(q,4,999)
q

7-element Vector{Int64}:
 -2
 -1
  3
  6
  7
  8
  9

In [80]:
A = [1 2 ; 3 4]
println(sum(A))
println(sum(A,dims=1))
println(sum(A,dims=2))
println(prod(A))
println(maximum(A))
println(minimum(A))

10
[4 6]
[3; 7;;]
24
4
1

In [103]:
x = rand(10)
println(x)
findall(>(0.3),x)

[0.606539863728943, 0.5777928522143645, 0.09838997374938596, 0.26286221322305003, 0.1705229774148912, 0.5784734062510021, 0.2852078233299866, 0.2691912184295743, 0.8132605760265043, 0.3071087275141068]


5-element Vector{Int64}:
  1
  2
  6
  9
 10

In [90]:
findfirst(<(0.7),x)

2

In [105]:
findnext(x,5) do v
  v ≤ 0.2 || v ≥ 0.8
end

5

In [110]:
b = BitVector([0,0,1,0,1]);
findlast(b)

5

In [111]:
findprev(b,4)

3

In [112]:
M = [3 1 4 ; 5 9 3]
println(findall(isodd,M))

2×3 Matrix{Int64}:
 3  1  4
 5  9  3

In [116]:
println(argmax(M))
println(argmax(M))

CartesianIndex(2, 2)

In [ ]:
println(argmax(M))