# 3-1便利な標準関数たち

## 3-1-1演算系(1) 除算・剰余算系

In [169]:
println(div(5,2), div(-5,2))#切り捨て
println(fld(5,2), fld(-5,2))#切り下げ　floor division
println(cld(5,2), fld(-5,2))#切り上げ　ceiling division

2-2
2-3
3-3


以下が表のマークダウン版です：

| 丸めモード | 説明 | 備考 |
|------------|------|------|
| RoundToZero | 切り捨て | デフォルト (div(x, y, RoundToZero) == div(x, y)) |
| RoundDown | 切り下げ | div(x, y, RoundDown) == fld(x, y) |
| RoundUp | 切り上げ | div(x, y, RoundUp) == cld(x, y) |
| RoundNearest | 最近接丸め（偶数） | x.5 の時は偶数 |
| RoundNearestTiesAway | 最近接丸め（0から遠い方） | x.5 の時は四捨五入 |
| RoundNearestTiesUp | 最近接丸め（切り上げ） | x.5 の時は切り上げ |


In [170]:
div(5,2,RoundNearestTiesAway)

3

In [171]:
÷(-5,2,RoundDown)

-3

- %,rem 整数剰余算(切り捨て)
- mod 整数剰余算(切り下げ)　

In [172]:
divrem(4.3,1.2)

(3.0, 0.7)

In [173]:
dayofweek(date) = mod1(days(date),7)
days_of_week = ["Monday" , "Tuesday" , "Wednesday" , "Thursday", "Friday" ,"Saturday" ,"Sunday"]
dayname(date) = days_of_week[dayofweek]

dayname (generic function with 1 method)

In [174]:
mod(2+2π , 2pi)
mod2pi(10)
rem2pi(80,RoundDown)

4.6017763138449626

行列演算では有用らしい

In [175]:
2\3

1.5

### 積和演算
x * y + z
- fma() 精度優先
- muladd() パフォーマンス優先

In [176]:
fma(0.1,0.2,0.3)
muladd(0.1,0.2,0.3)

0.32

### 剰余演算

オーバーフローしないようになっている

In [177]:
powermod(5,2,20) # == mod(5^2,20)

5

## 3-1-2 演算系(2)結合演算

## 3-1-3演算系(3)その他の演算系関数

| 関数       | 説明                                                 |
|------------|------------------------------------------------------|
| sign(x)    | 符号関数 1 (x > 0) / -1 (x < 0) / 0 (x == 0)          |
| signbit(x) | 符号関数 true (x < 0) / false (x ≥ 0)                 |
| cmp(x, y)  | 比較関数 1 (x > y) / -1 (x < y) / 0 (x == y)          |
| abs(x)     | 絶対値関数                                           |
| abs2(x)    | 絶対値の2乗を返す関数                                |
| copysign(x, y) | xをabs(x)とy相当 (ただしy == 0のときはx)           |
| flipsign(x, y) | x * sign(y) 相当 (ただしy == 0のときはx)          |
| sqrt(x)    | 平方根関数 (演算子)                                  |
| isqrt(x)   | 整数平方根関数                                       |
| cbrt(x)    | 立方根関数 (演算子)                                  |


| 関数 | 説明 |
|------|------|
| sin(x) | 三角関数: 正弦関数 (sin x) |
| cos(x) | 三角関数: 余弦関数 (cos x) |
| tan(x) | 三角関数: 正接関数 (tan x) |
| asin(x) | 三角関数: 正弦関数の逆関数 (arcsin x) |
| acos(x) | 三角関数: 余弦関数の逆関数 (arccos x) |
| atan(x) | 三角関数: 正接関数の逆関数 (arctan x) |
| atan(x, y) | 三角関数: 正接関数の逆関数 (arctan x/y) |
| exp(x) | 指数関数 (eˣ) |
| log(x) | 対数関数：自然対数 (log_e x または ln x) |
| log(b, x) | 対数関数：底を b とする対数 (log_b x) |
| sinh(x) | 双曲線関数正弦関数 (sinh x) |
| cosh(x) | 双曲線関数余弦関数 (cosh x) |
| tanh(x) | 双曲線関数正接関数 (tanh x) |
| sec(x) | 三角関数: 正割関数 (sec x, 1/cos(x) 相当) |
| csc(x) | 三角関数: 余割関数 (csc x, 1/sin(x) 相当) |
| cot(x) | 三角関数: 余接関数 (cot x, 1/tan(x) 相当) |
| asec(x) | 三角関数: 正割関数の逆関数 |
| acsc(x) | 三角関数: 余割関数の逆関数 |
| acot(x) | 三角関数: 余接関数の逆関数 |
| logℯ(x) | 対数関数: 常用対数 (log₁₀x), log(10, x) 相当 |
| log2(x) | 対数関数: 底を2とする対数 (log₂x), log(2, x) 相当 |
| log1p(x) | 対数関数, log(x + 1) 相当 |
| deg2rad(x) | 度→ラジアンの変換関数, π*x/180 相当 |
| rad2deg(x) | ラジアン→度の変換関数, 180*x/π 相当 |
| sind(x) | 三角関数: 正弦関数, sin(deg2rad(x)) 相当 |
| cosd(x) | 三角関数: 余弦関数, cos(deg2rad(x)) 相当 |
| tand(x) | 三角関数: 正接関数, tan(deg2rad(x)) 相当 |
| asind(x) | 三角関数: 正弦関数の逆関数, rad2deg(asin(x)) 相当 |
| acosd(x) | 三角関数: 余弦関数の逆関数, rad2deg(acos(x)) 相当 |
| atand(x) | 三角関数: 正接関数の逆関数, rad2deg(atan(x)) 相当 |
| secd(x) | 三角関数: 正割関数, sec(deg2rad(x)) 相当 |
| cscd(x) | 三角関数: 余割関数, csc(deg2rad(x)) 相当 |
| cotd(x) | 三角関数: 余接関数, cot(deg2rad(x)) 相当 |
| asecd(x) | 三角関数: 正割関数の逆関数, rad2deg(asec(x)) 相当 |
| acscd(x) | 三角関数: 余割関数の逆関数, rad2deg(acsc(x)) 相当 |
| acotd(x) | 三角関数: 余接関数の逆関数, rad2deg(acot(x)) 相当 |
| sinpi(x) | 三角関数: 正弦関数, sin(π*x) 相当 |
| cospi(x) | 三角関数: 余弦関数, cos(π*x) 相当 |
| tanpi(x) | 三角関数: 正接関数, tan(π*x) 相当 |
| sincos(x) | (sin(x), cos(x)) 相当 |
| sincospi(x) | (sinpi(x), cospi(x)) 相当 |
| sinc(x) | カーディナルサイン関数 : sin(π*x)/(π*x) 相当 |
| cosc(x) | sinc(x) の導関数 |
| cis(x) | 指数関数, exp(x*im) 相当 |
| cispi(x) | 指数関数, cis(π*x) 相当 |

## 3-1-5 数学系(2) その他の数学関数
| 関数 | 説明 |
|------|------|
| factorial(n) | 階乗 (n!) |
| binomial(n, m) | 二項係数 (ₙCₘ) |
| gcd(a, b...) | 最大公約数 (引数可変個) |
| lcm(a, b...) | 最小公倍数 (引数可変個) |
| gcdx(a, b) | 最大公約数+ベズー係数 (戻り値は3値タプル) |

## 3-1-6文字・文字列情報取得関数

### 文字・文字列情報取得関数・演算子
| 関数・演算子 | 説明 | 例 |
|-------------|------|-----|
| length(s) | 文字列長 | length("123ABCあいう漢字") == 11 |
| sizeof(s) | 文字列のバイト長 | sizeof("123ABCあいう漢字") == 21 (※1) |
| ncodeunits(s) | 文字列のコードユニット数 | ncodeunits("123ABCあいう漢字") == 21 (※1) |
| isempty(s) | 空文字列判定 | isempty("") == true |
| codepoint(c) | 文字のユニコードコードポイント | codepoint('A') == 0x00000041, codepoint('あ') == 0x00003042 |
| codeunits(s) | 文字列のコードユニット列 | codeunits("ABC漢字") == UInt8[0x41, 0x42, 0x43, 0xe6, 0xbc, 0xa2, 0xe5, 0xad, 0x97] |
| codeunits(s, i) | 文字列の指定位置のコードユニット値 | codeunits(s)[i] 相当 |
| s[i] | インデクシング | "ABCDE"[4] == 'D', "ABCDE"[2:4] == "BCD" |
| @view s[i] | 部分文字列抽出 | @view "ABCDE"[2:4] == SubString("ABCDE", 2, 4) == "BCD" |
| first(s) | 文字列の最初の文字 | first("ABCDE") == 'A', first("あいうえお") == 'あ' |
| first(s, n) | 文字列の最初のn文字を抽出 | first("ABCDE", 1) == "A", first("あいうえお", 3) == "あいう" |
| last(s) | 文字列の末尾の文字 | last("ABCDE") == 'E', last("あいうえお") == 'お' |
| last(s, n) | 文字列の末尾のn文字を抽出 | last("ABCDE", 1) == "E", last("あいうえお", 3) == "うえお" |
| firstindex(s) | 文字列の最初のインデックス | firstindex("ABC") == 1, firstindex("あいう") == 1 |
| lastindex(s) | 文字列の最後のインデックス | lastindex("ABC") == 3, lastindex("あいう") == 7 |
| thisind(s, i) | i バイト目が属する文字のインデックス | thisind("ABC", 3) == 3, thisind("あいう", 3) == 1, thisind("あいう", 4) == thisind("あいう", 5) == 4 |
| nextind(s, i) | i バイト目よりも後の最初の文字のインデックス | nextind("ABC", 2) == 3, nextind("あいう", 2) == 4, nextind("あいう", 4) == nextind("あいう", 5) == 7 |
| prevind(s, i) | i バイト目よりも前の最後の文字のインデックス | prevind("ABC", 2) == 1, prevind("あいう", 7) == 4, prevind("あいう", 4) == prevind("あいう", 3) == 1 |
| eachindex(s), keys(s) | 文字列のインデックスを列挙 | collect(eachindex("あいう")) == collect(keys("あいう")) == [1, 4, 7] |
| textwidth(s) | 文字列の表示幅 | textwidth('A') == 1, textwidth('あ') == 2, textwidth("ABC") == 3, textwidth("あいう") == 6 |

### 文字・文字列比較関数・演算子
- == 等価演算子
- != ,≠ 非等価演算子
- < <= > >=
- cmp 辞書式大小比較
- c in S \in \notin

### 文字列操作関数・演算子
- string(v..) 文字列化関数
- s*t 文字列連結
- s^n , repeat(s,n) 文字列リピート
- uppercase(s) 小文字を大文字に変換
- lowercase(s) 大文字を小文字に変換
- uppercasefirst(s) 文字列の最初の文字を大文字に変換
- lowercasefirst(s)
- titlecase(s) 文字列の最初の文字を大文字に，それ以外を小文字に
- join(collection ,delim)コレクションの各要素をdelimで連結した文字列を生成
- chop(s) 文字列の末尾の文字除去
- chomp(s) 文字列末尾の改行文字除去
- split(s) rsplit(s) ホワイトスペースによる文字列分割
- split(s,pattern) rsplit(s,pattern) patternによる文字列分割
- strip(s) lstrip(s) rstrip(s) 文字列の先頭，末尾のホワイトスペースの除去
- strip(s,chars),lstrip(s,chars),rstrip(s,chars) 文字列の先頭/末尾の特定文字の除去
- strip(fn,s),lstrip(fn,s),rstrip(fn,s) 文字列の先頭/末尾の特定文字の除去
- lpad(s,l.pad=' '),rpad(s,l,pad=' ') 文字列の行埋め
- reverse() 文字列反転

### 文字列検索･置換関連関数
- match(r::Regex, s) 正規表現マッチ
- each(r::Regex, s) 正規表現マッチイテレーション
- findfirst(pattern .s,) パターン検索(先頭から)
- findnext(patten,s,i) パターン検索(iバイト目以降)
- findlast(ptnstr,s) 文字列検索(末尾から)
- findprev(prnstr, s, i)文字列検索(iバイト目以前)
- findall(pattern,s) パターン検索
- count(patten,s) パターン検索(件数)
- occursin(patten,s) パターンが含まれるか否か
- contains(s,pattern) 同上
- startswith(s,pattern) パターンで始まるか否か
- endswith(s,pattern) パターンで終わるか否か
- replace(s,patten=>subst) 文字列置換

### Julia の正規表現
- ^ 先頭 
- | 代替
- . 任意の1文字
- * 直前のパターンの0回以上の繰り返し
- + 直前のパターンの1回以上の繰り返し
- {n,m} 直前のパターンのn回以上m回以下の繰り返し {n} n回の繰り返し
- [a-z] 文字クラス
- \s ホワイトスペース
- \d 数字
- \w 単語構成文字
- (...) キャプチャグループ
- (?<name>...) 名前付きキャプチャグループ

#### 正規表現のモードフラグ
- i 大文字小文字区別しない
- m 複数行モード
- s 任意の1文字が改行にもマッチ
- a ASCIIモード
- x コメントモード

In [178]:
m = match(r"\d+","123dfaisfjhaklj54") 
m.match

"123"

In [179]:
m = match(r"(\d+)(?<ABC>[ABC]+)","123ABCdfaisfABCjhaklj54") 
m.match

"123ABC"

In [180]:
for m in eachmatch(r"\w+","Yes, I have a number.")
  println(m.match)
end

Yes
I
have
a
number


- \0 マッチした部分文字列 m.match
- \1 \2 キャプチャグループ
- \g<1> 
- \g < name >

In [181]:
replace("123ABCあいう漢字",r"\d"=> s"\0\0")

"112233ABCあいう漢字"

In [182]:
replace("123ABCあいう漢字",r"\d"=> s"\g<0>1")

"112131ABCあいう漢字"

In [183]:
replace("123ABCあいう漢字",r"(\d+)(?<abc>[a-z]+)"ia=>s"\g<abc>\1")

"ABC123あいう漢字"

- length
- isempty
- in A 
- eltype
- ndims
- size 配列のサイズ
- axes インデックス範囲

In [184]:
A = [100z + 10y + x for x = 1:3 ,y = 1:4 , z= 1:2];
ndims(A)

3

In [185]:
size(A)

(3, 4, 2)

In [186]:
axes(A)

(Base.OneTo(3), Base.OneTo(4), Base.OneTo(2))

In [187]:
axes(A,2)

Base.OneTo(4)

In [188]:
for x in axes(A,1) ,y in axes(A,2) ,z in axes(A,3)
  println(A[x,y,z])
end

111
211
121
221
131
231
141
241
112
212
122
222
132
232
142
242
113
213
123
223
133
233
143
243


## 3-1-7配列生成演算子

In [189]:
axes((:a,:b,:c))

(Base.OneTo(3),)

In [190]:
Vector{Int}(undef,5)

5-element Vector{Int64}:
               1
               3
 128907801189840
 128907801189904
 128907785114368

In [191]:
Matrix{Float64}(undef,2,2)

2×2 Matrix{Float64}:
 6.36889e-310  0.0
 6.36889e-310  0.0

In [192]:
Array{UInt8}(undef,2,3,2)

2×3×2 Array{UInt8, 3}:
[:, :, 1] =
 0x90  0xab  0x3d
 0x57  0xb0  0x75

[:, :, 2] =
 0x00  0xe0  0xa9
 0x00  0x83  0xae

In [193]:
zeros(Int,5)

5-element Vector{Int64}:
 0
 0
 0
 0
 0

In [194]:
ones(2,2)

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [195]:
fill(0x7f,2,2)

2×2 Matrix{UInt8}:
 0x7f  0x7f
 0x7f  0x7f

In [196]:
BitArray(undef,12,13)

12×13 BitMatrix:
 0  0  1  1  0  0  0  0  1  1  0  0  0
 0  0  0  1  0  0  1  1  0  1  0  0  0
 0  0  1  0  0  0  0  1  1  1  0  0  0
 0  0  0  0  0  0  0  1  1  0  0  0  0
 1  0  1  1  0  0  0  1  1  0  0  0  0
 0  0  1  0  0  0  1  0  1  0  0  0  0
 1  0  1  1  0  0  0  1  0  0  0  0  0
 1  0  1  0  0  0  0  0  0  0  0  0  0
 1  0  1  1  0  1  0  1  1  0  0  0  0
 1  1  0  1  0  0  0  1  0  0  0  0  0
 0  1  1  1  0  1  0  1  1  0  0  0  0
 1  1  1  0  0  0  0  1  0  0  0  0  0

In [197]:
trues(3,4,2)

3×4×2 BitArray{3}:
[:, :, 1] =
 1  1  1  1
 1  1  1  1
 1  1  1  1

[:, :, 2] =
 1  1  1  1
 1  1  1  1
 1  1  1  1

In [198]:
typeof(1:2:10 .== [2,33,34,12,30])

BitVector (alias for BitArray{1})

In [199]:
A = UInt8[1 2 ; 3 4]

2×2 Matrix{UInt8}:
 0x01  0x02
 0x03  0x04

In [200]:
similar(A,3,4,2)

3×4×2 Array{UInt8, 3}:
[:, :, 1] =
 0x08  0x00  0x00  0x2f
 0x00  0x00  0x00  0x96
 0x00  0x00  0xb0  0xec

[:, :, 2] =
 0x3d  0x00  0x96  0x75
 0x75  0x00  0xec  0x00
 0x00  0x0e  0x3d  0x00

In [201]:
similar(A,Float32)

2×2 Matrix{Float32}:
 -6.28507f32  -1.26196f-9
  4.2057f-41   4.2057f-41

In [202]:
B = BitArray(undef,2,2)

2×2 BitMatrix:
 0  0
 0  0

In [203]:
similar(B,10)

10-element BitVector:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [204]:
A = [1 2 ;3 4];
x = [-1 ; 1];
y = A*x

2-element Vector{Int64}:
 1
 1

In [205]:
A = [1 2 ; 3 4];
x = [-1 : 1];
println(transpose(A))
println(A')
println(A'A)
C = [1-1im 2 + 3im ; 3ℯ^2 + im  π]
println(transpose(C))
println(C')

[1 3; 2 4]
[1 3; 2 4]
[10 14; 14 20]
ComplexF64[1.0 - 1.0im 22.16716829679195 + 1.0im; 2.0 + 3.0im 3.141592653589793 + 0.0im]
ComplexF64[1.0 + 1.0im 22.16716829679195 - 1.0im; 2.0 - 3.0im 3.141592653589793 - 0.0im]


In [206]:
q = [1,2,3,4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [207]:
push!(q,12,32)

6-element Vector{Int64}:
  1
  2
  3
  4
 12
 32

In [208]:
pop!(q)

32

In [209]:
pop!(q)

12

In [210]:
q

4-element Vector{Int64}:
 1
 2
 3
 4

In [211]:
pushfirst!(q,-2,-1)

6-element Vector{Int64}:
 -2
 -1
  1
  2
  3
  4

In [212]:
popfirst!(q)

-2

In [213]:
prepend!(append!(q, 6:9),-2:0)

12-element Vector{Int64}:
 -2
 -1
  0
 -1
  1
  2
  3
  4
  6
  7
  8
  9

In [214]:
popat!(q,4)
q

11-element Vector{Int64}:
 -2
 -1
  0
  1
  2
  3
  4
  6
  7
  8
  9

In [215]:
deleteat!(q,3:4)

9-element Vector{Int64}:
 -2
 -1
  2
  3
  4
  6
  7
  8
  9

In [216]:
popat!(q,4,999)
q

8-element Vector{Int64}:
 -2
 -1
  2
  4
  6
  7
  8
  9

In [217]:
A = [1 2 ; 3 4]
println(sum(A))
println(sum(A,dims=1))
println(sum(A,dims=2))
println(prod(A))
println(maximum(A))
println(minimum(A))

10
[4 6]
[3; 7;;]
24
4
1


In [218]:
x = rand(10)
println(x)
findall(>(0.3),x)

[0.9021568061073044, 0.22130907944079514, 0.4374194301012395, 0.7153076929528496, 0.7861123140648587, 0.9766786466791769, 0.1639650402025633, 0.8264786985466525, 0.2904008986863704, 0.3518973525157739]


7-element Vector{Int64}:
  1
  3
  4
  5
  6
  8
 10

In [219]:
findfirst(<(0.7),x)

2

In [220]:
findnext(x,5) do v
  v ≤ 0.2 || v ≥ 0.8
end

6

In [221]:
b = BitVector([0,0,1,0,1]);
findlast(b)

5

In [222]:
findprev(b,4)

3

In [223]:
M = [3 1 4 ; 5 9 3]
println(findall(isodd,M))

CartesianIndex{2}[CartesianIndex(1, 1), CartesianIndex(2, 1), CartesianIndex(1, 2), CartesianIndex(2, 2), CartesianIndex(2, 3)]


In [224]:
println(argmax(M))

CartesianIndex(2, 2)


### 辞書関連関数

In [225]:
D = Dict(:a=>1, :b=>2, :c=>3)

Dict{Symbol, Int64} with 3 entries:
  :a => 1
  :b => 2
  :c => 3

In [226]:
keytype(D)

Symbol

In [227]:
valtype(D)

Int64

In [228]:
keys(D)

KeySet for a Dict{Symbol, Int64} with 3 entries. Keys:
  :a
  :b
  :c

In [229]:
collect(values(D))

3-element Vector{Int64}:
 1
 2
 3

In [230]:
haskey(D ,:a) # :a ∈ keys(D)に同じ 

true

In [231]:
D[:a]

1

get(D, key, default)

In [232]:
get(D,:a,-99)

1

In [233]:
get(D,:d,-99)

-99

 get!()はキーが存在しなかった場合にそのキーのエントリーとして登録

In [234]:
get!(D, :d, 4)
D[:d]

4

In [235]:
push!(D, :b=>4, :d=>5, :e=>3, :f=>17)

Dict{Symbol, Int64} with 6 entries:
  :a => 1
  :b => 4
  :f => 17
  :d => 5
  :e => 3
  :c => 3

In [236]:
delete!(D, :e)

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 4
  :f => 17
  :d => 5
  :c => 3

In [237]:
pop!(D, :a)
D

Dict{Symbol, Int64} with 4 entries:
  :b => 4
  :f => 17
  :d => 5
  :c => 3

In [238]:
pop!(D, :a, -99)

-99

In [239]:
D1 = Dict(:a=>1, :b=>2, :c=>3);
D2 = Dict(:b=>4, :d=>5, :f=>6);
merge(D1,D2)

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 4
  :f => 6
  :d => 5
  :c => 3

In [240]:
merge(D2,D1)

Dict{Symbol, Int64} with 5 entries:
  :f => 6
  :b => 2
  :a => 1
  :d => 5
  :c => 3

In [241]:
mergewith(+,D1,D2)

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 6
  :f => 6
  :d => 5
  :c => 3

In [242]:
mergewith(D1,D2) do a,b
  100a + b
end

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 204
  :f => 6
  :d => 5
  :c => 3

In [243]:
merge!(D1,D2) #D1が更新される
D1

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 4
  :f => 6
  :d => 5
  :c => 3

In [244]:
mergewith!(-,D1,D2)

Dict{Symbol, Int64} with 5 entries:
  :a => 1
  :b => 0
  :f => 0
  :d => 0
  :c => 3

### 集合関連関数・演算子

In [245]:
S1 = Set([1,2,3]);
S2 = Set([2,4,5]);

In [246]:
S1∩S2

Set{Int64} with 1 element:
  2

In [247]:
S1∪S2

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [248]:
S0 = Set(1:10);
intersect!(S0,S1,S2) #S0が更新される

Set{Int64} with 1 element:
  2

In [249]:
union!(S0,S1,S2);
S0

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [250]:
setdiff(S1,S2) #S1\S2

Set{Int64} with 2 elements:
  3
  1

In [251]:
S0 = Set(1:10)
setdiff!(S0,S1,S2);
S0

Set{Int64} with 5 elements:
  6
  7
  10
  9
  8

In [252]:
symdiff(S1,S2) #S1 ◬ S2

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [253]:
S = Set(Int[]);
push!(S,1,2,3)

Set{Int64} with 3 elements:
  2
  3
  1

In [254]:
delete!(S,1)

Set{Int64} with 2 elements:
  2
  3

In [255]:
delete!(S,100) #エラーにならない

Set{Int64} with 2 elements:
  2
  3

In [256]:
push!(S,2);
pop!(S,2)

2

In [257]:
pop!(S,2,-99)

-99

### タプル・名前付きタプル関連関数

In [258]:
t = ('a', 2, 99.9, π)

('a', 2, 99.9, π)

In [259]:
first(t)

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [260]:
last(t)

π = 3.1415926535897...

In [261]:
Base.front(t) #最初の要素以外からなるタプル

('a', 2, 99.9)

In [262]:
Base.tail(t)

(2, 99.9, π)

In [263]:
nt = (a=1, b=2, c=3, π);
keys(nt)

(:a, :b, :c, :π)

In [264]:
values(nt)

(1, 2, 3, π)

In [265]:
haskey(nt,:a)

true

In [266]:
s = "あいうえお";
merge(nt, (a=1,b=1,s))

(a = 1, b = 1, c = 3, π = π, s = "あいうえお")

In [267]:
merge(nt, [:a=>1, :b=>2, :c=>3, :d=>4, :e=>5])

(a = 1, b = 2, c = 3, π = π, d = 4, e = 5)

## その他あると便利がある関数
- max()
- min()
- minmax() #最大値と最小値
- invmod(n,m) mを法としたnの逆数
- clamp(x,lo,hi) lo $\leq x \leq$ hiとなるように$x$を調節
- clamp(n, ::Type{T}) 型Tで表現できる範囲でclamp
- clamp(A,lo,hi)
- issorted(A) ソート済みかどうか
- sort(A) ベクトルをソート
- reverse(A)　配列を逆順に

In [268]:
+(1)

1

In [269]:
+(1,2)

3

In [270]:
+(1,2,3)

6

In [271]:
÷(5,2)

2

In [272]:
÷(5,2,RoundDown)

2

In [273]:
÷(5,2,RoundUp)

3

In [274]:
÷(5,2,RoundNearest)

2

In [275]:
÷(5,2,RoundNearestTiesUp)

3

In [277]:
v = 1.0e-10

1.0e-10

In [278]:
v ≈ 0

false

In [279]:
≈(v, 0.0, atol=1e-8)

true

- ==(y) 
- !=(y), $\neq$(y)
- <(y)
- <=(y) $\leq$(y)
- \>(y)
- \>=(y) $\geq$(y)
- in(A), $\in$(A)
- $\notin$(A)
- $\ni$(y)
- $\notni$(y)
- $\approx$(y)
- $\not\approx$(y)

In [280]:
is1to10 = ∈(1:10);
is1to10(3)

true

In [281]:
is1to10(12)

false

# 3-2標準ライブラリ


| パッケージ | 概要 |
|------------|------|
| Artifacts | パッケージとは別のデータコンテナ（=アーティファクト）の管理 |
| Base64 | Base64エンコード/デコード機能 |
| CRC32c | CRC-32c チェックサム計算機能 |
| Dates | 日時計算ライブラリ |
| DelimitedFiles | CSV (TSV含む) 形式読み書きの基本機能ライブラリ |
| Distributed | 分散処理ライブラリ |
| Downloads | ファイルダウンロード処理ライブラリ |
| FileWatching | ファイル/ディレクトリ監視機能 |
| Future | 既存機能（関数）の将来実装を提供するパッケージ |
| InteractiveUtils | インタラクティブモード（REPL、JupyterNotebook等）で提供される機能 |
| LazyArtifacts | アーティファクト遅延ダウンロードのための依存パッケージ |
| LibGit2 | libgit2 バインディングライブラリ |
| Libdl | 共有ライブラリロード機能 |
| LinearAlgebra | 線型代数計算ライブラリ |
| Logging | ロギングライブラリ |
| Markdown | マークダウンライブラリ |
| Mmap | メモリマップファイルI/Oライブラリ |
| Pkg | Juliaのパッケージ管理機能（第10章参照） |
| Printf | 書式化出力ライブラリ |
| Profile | プロファイリング機能 |
| REPL | REPL機能 |
| Random | 乱数関連ライブラリ |
| SHA | SHAハッシュエンコードライブラリ |
| Serialization | シリアル化ライブラリ |
| SharedArrays | プロセス間メモリ共有ライブラリ |
| Sockets | ネットワークソケットライブラリ |
| SparseArrays | 疎行列（疎配列）基本ライブラリ |
| Statistics | 統計計算ライブラリ |
| SuiteSparse | 疎行列の線型代数計算ライブラリ |
| TOML | TOML解析/出力処理ライブラリ |
| Test | ユニットテストライブラリ |
| UUIDs | UUID生成機能 |
| Unicode | Unicode処理機能 |

## 3-2-1 Printf

| 関数・マクロ名 | 説明 | 備考 |
|----------------|------|------|
| @printf("《書式文字列》", ...) | 書式化文字列出力マクロ | 出力先は標準出力 |
| @printf(io, "《書式文字列》", ...) | 書式化文字列出力マクロ | 第1引数の IO オブジェクトに出力 |
| @sprintf("《書式文字列》", ...) | 書式化文字列生成マクロ | 結果は文字列 |
| Printf.format("《書式文字列》") | 書式化文字列リテラル | |
| Printf.Format("《書式文字列》") | 書式文字列コンストラクタ | |
| Printf.format(format::Printf.Format, ...) | 書式化文字列生成 | 戻り値は文字列 |
| Printf.format(io, format::Printf.Format, ...) | 書式化文字列出力 | 第1引数の IO オブジェクトに出力 |

In [10]:
using Printf
x = 23.4348975
@printf("%d",x)

23

In [13]:
@printf("%.2f",x) #小数点2桁

23.43

In [16]:
@printf("%.10g",x) #小数点以外で10桁 ただし非表示

23.4348975

In [18]:
@printf(stderr,"%d",x) #標準エラー出力に出力

23

ファイルに出力

In [20]:
open("sampleout.txt","w") do f
  @printf(f,"%d",x)
end

## 3-2-2 Dates

| 関数・演算子 | 説明 | 備考 |
|-------------|------|------|
| now() | 現在日時の取得 | 戻り値は DateTime 型 |
| Year(n) | 年間 | 例：Year(1) |
| Quarter(n) | 四半期 | 例：Quarter(2) |
| Month(n) | 期間：n か月 | 例：Month(3) |
| Week(n) | 期間：n 週間 | 例：Week(4) |
| Day(n) | 期間：n 日 | 例：Day(5) |
| Hour(n) | 期間：n 時間 | 例：Hour(6) |
| Minute(n) | 期間：n 分 | 例：Minute(7) |
| Second(n) | 期間：n 秒 | 例：Second(8) |
| Millisecond(n) | 期間：n ミリ秒 | 例：Millisecond(9) |
| Microsecond(n) | 期間：n マイクロ秒 | 例：Microsecond(999) |
| Nanosecond(n) | 期間：n ナノ秒 | 例：Nanosecond(999) |
| dt + period, dt + period | 日付の加算 | dt は Date, period は Year~Day, 戻り値は Date |
| tm + period, tm + period | 時刻の加算 | tm は Time, period は Hour~Nanosecond, 戻り値は Time |
| dtm + period, dtm + period | 日時の加算 | dtm は DateTime, period は Year~ Millisecond, 戻り値は DateTime |
| dt1 - dt2 | 日付の差 | dt1, dt2 は Date, 戻り値は Day |
| tm1 - tm2 | 時刻の差 | tm1, tm2 は Time, 戻り値は Nanosecond |
| dtm1 - dtm2 | 日時の差 | dtm1, dtm2 は DateTime, 戻り値は Millisecond |
| dt1:period:dt2 | 日付の範囲 | dt1, dt2 は Date, period (ステップ幅) は Year ~Day |
| tm1:period:tm2 | 時刻の範囲 | tm1, tm2 は Time, period (ステップ幅) は Hour ~Nanosecond |
| dtm1:period:dtm2 | 日時の範囲 | dtm1, dtm2 は DateTime, period (ステップ幅) は Year~Millisecond |
| dateformat("文字列") | 日付書式化文字列定義 | 例：dateformat("yyyy/mm/dd HH:MM:SS") |
| Dates.format(dts, dateformat("~")) | 日時書式化文字列変換 | dts は Date/Time/DateTime |
| Date("日付文字列", dateformat("~")) | 日付文字列の解析 | 例：Date("2017/9/5", dateformat("yyyy/mm/dd")) # 2017-09-05, Date型 |
| Time("時刻文字列", dateformat("~")) | 時刻文字列の解析 | 例：Time("20:52:10", dateformat("HH:MM:SS")) # 20:52:10, Time型 |
| DateTime("日時文字列", dateformat("~")) | 日時文字列の解析 | 例：DateTime("2020-02-03T23:59:53.012", dateformat("yyyy-mm-ddTHH:MM:SS.sss")) # 2020-02-03T23:59:53.012, DateTime型 |
| isleapyear(dt) | 閏年かどうか | 例：isleapyear(Date(2000)) == true |
| monthname(dt) | 月名（英語） | 例：monthname(Date(2000, 1, 1)) == "January" |
| dayname(dt) | 曜日（英語） | 例：dayname(Date(2000, 1, 1)) == "Saturday" |